services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      -  /etc/localtime:/etc/localtime:ro 
      -  /etc/timezone:/etc/timezone:ro 
    environment:
      MYSQL_ROOT_PASSWORD: "root-password-change-me"
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: "bdklriorjgptoh"
    restart: unless-stopped

  semaphore:
    container_name: ansiblesemaphore
    image: semaphoreui/semaphore:v2.8.90
    user: "${UID}:${GID}"
    ports:
      - "80:3000"

    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: "bdklriorjgptoh"
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: "3306"
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore

      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: "Admin1234!"
      SEMAPHORE_ADMIN_NAME: "Admin"
      SEMAPHORE_ADMIN_EMAIL: admin@localhost

      SEMAPHORE_ACCESS_KEY_ENCRYPTION: "mFSb1VNKQF1tW5o3RzxD9pLjHsYeKwNc"
      SEMAPHORE_PLAYBOOK_PATH: /ansible/playbooks

    volumes:
      - ./inventory/:/inventory:ro
      - ./authorized-keys/:/authorized-keys:ro
      - ./config/:/etc/semaphore:rw
      -  /etc/localtime:/etc/localtime:ro 
      -  /etc/timezone:/etc/timezone:ro 

    restart: unless-stopped
    depends_on:
      - mysql
