---
- name: Restart Odoo and Nginx
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: Restart Odoo
      ansible.builtin.command:
        cmd: docker compose restart
        chdir: "{{ ansible_env.HOME }}/server.odoo"

    - name: Restart Nginx
      ansible.builtin.command:
        cmd: docker compose restart
        chdir: "{{ ansible_env.HOME }}/server.proxy"