---
- name: Stop Odoo and Nginx
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: Stop Nginx
      ansible.builtin.command:
        cmd: docker compose down
        chdir: "/home/{{ ansible_user }}/server.proxy"

    - name: Stop Odoo
      ansible.builtin.command:
        cmd: docker compose down
        chdir: "/home/{{ ansible_user }}/server.odoo"